[build]
  command = "CI=false npm run build && cp public/optin.html build/optin.html"
  publish = "build"

[[redirects]]
  from = "/optin"
  to = "/optin.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
